version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"  # Interne, pour Docker

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"  # Interne, pour Docker

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Accessible depuis localhost
    depends_on:
      - frontend
      - backend
